solidusio/solidus_graphql_api

spec/spec_helper.rb
Enabled cache causes random problems in BatchLoader specs execution.
For more info:
https://github.com/exAspArk/batch-loader#caching
=> Disable the cache for all the `BatchLoader` run in the tests

lib/spree/graphql/types/product_property.rb, lib/spree/queries/product_property/property_query.rb, spec/lib/spree/graphql/types/product_property_spec.rb, spec/lib/spree/queries/product_property/property_query_spec.rb
Add `ProductProperty` Type that will be used in the `Product` Type.
It has basic fields and the `property` field loaded with the batch loader inside a query object.
=> Add ProductProperty Type

lib/spree/graphql/types/option_type.rb, lib/spree/graphql/types/product.rb, lib/spree/graphql/types/query.rb, lib/spree/queries/product/master_variant_query.rb, lib/spree/queries/product/option_types_query.rb, lib/spree/queries/product/variants_query.rb, lib/spree/queries/products_query.rb, schema.graphql, spec/expected_schema.graphql, spec/integration/products_spec.rb, spec/lib/spree/graphql/types/product_spec.rb, spec/lib/spree/graphql/types/query_spec.rb, spec/lib/spree/queries/product/master_variant_query_spec.rb, spec/lib/spree/queries/product/option_types_query_spec.rb, spec/lib/spree/queries/product/variants_query_spec.rb, spec/lib/spree/queries/products_query_spec.rb, spec/queries/products.gql
Add `products` field to the root query, the Product Type has the basic fields, `variants` and `option_types` connections, and the `master variant`.
=> Add products field to the root query

lib/spree/graphql/types/address.rb, lib/spree/queries/address/country_query.rb, lib/spree/queries/address/state_query.rb, spec/lib/spree/graphql/types/address_spec.rb, spec/lib/spree/queries/address/country_query_spec.rb, spec/lib/spree/queries/address/state_query_spec.rb
Add `AddressType`. It will be used in the [`UserType`](#12):
=> Add Address type

lib/spree/graphql/types/query.rb, lib/spree/queries/product_by_slug_query.rb, schema.graphql, spec/expected_schema.graphql, spec/integration/product_by_slug_spec.rb, spec/lib/spree/graphql/types/query_spec.rb, spec/lib/spree/queries/product_by_slug_query_spec.rb, spec/queries/product_by_slug.gql
The `product_by_slug` field uses the `Spree::Queries::ProductBySlugQuery`
object to retrieve the product by its slug.
=> Add product_by_slug field to root query

.circleci/config.yml
Update the ruby image:
from: circleci/ruby:2.5.0-node
to: circleci/ruby:2.5.6-node
To align the configuration with the ruby version used in the `solidusio/extensions` orb.
For more information:
https://github.com/solidusio/circleci-orbs-extensions/commit/42a30abeadd7f60c294bd964d50f0c539842ff34#diff-e7ad19500a51f86882a1e250e92cb28d
=> Update ruby image on CircleCI

lib/spree/graphql/batch_loader.rb, lib/spree/graphql/batch_loader/belongs_to.rb, lib/spree/graphql/batch_loader/has_many.rb, lib/spree/graphql/batch_loader/has_many_through.rb, lib/spree/graphql/batch_loader/has_one.rb, lib/spree/graphql/schema.rb, lib/spree/queries/address/country_query.rb, lib/spree/queries/address/state_query.rb, lib/spree/queries/country/states_query.rb, lib/spree/queries/option_type/option_values_query.rb, lib/spree/queries/product/master_variant_query.rb, lib/spree/queries/product/option_types_query.rb, lib/spree/queries/product/product_properties_query.rb, lib/spree/queries/product/variants_query.rb, lib/spree/queries/product_property/property_query.rb, lib/spree/queries/taxon/children_query.rb, lib/spree/queries/taxon/parent_taxon_query.rb, lib/spree/queries/taxonomy/root_taxon_query.rb, lib/spree/queries/taxonomy/taxons_query.rb, lib/spree/queries/variant/option_values_query.rb, lib/spree/queries/variant/prices_query.rb, solidus_graphql_api.gemspec, spec/lib/spree/graphql/batch_loader/belongs_to_spec.rb, spec/lib/spree/graphql/batch_loader/has_many_spec.rb, spec/lib/spree/graphql/batch_loader/has_many_through_spec.rb, spec/lib/spree/graphql/batch_loader/has_one_spec.rb, spec/lib/spree/queries/product/master_variant_query_spec.rb, spec/spec_helper.rb
This implements a batch-loading framework that creates a layer on top of [batch-loader](https://github.com/exAspArk/batch-loader) to allow us to batch-load with a single line of code:
```ruby
Spree::Graphql::BatchLoader.for(user, :posts)
```
The class will automatically recognize the association type and use the appropriate batch-loading logic. It also allows to customize certain aspects of the batch-loading process (YARD documentation is provided for the different options), for instance by allowing to pass a custom scope to the association.
- We may consider extracting this into a separate gem, since it is completely independent from Solidus/GraphQL. The only improvement to do in this case would be to allow people to choose if they want to use `BatchLoader` or `BatchLoader::GraphQL`.
=> Batch loading framework

lib/spree/graphql/types/query.rb, lib/spree/graphql/types/user.rb, schema.graphql, spec/expected_schema.graphql, spec/integration/current_user_spec.rb, spec/queries/currentUser.gql, spec/support/helpers/graphql.rb, spec/support/shared_examples/query_is_successful.rb
The `current_user` field returns the `context[:current_user]` in form of ` Types::User`.
If the user isn't logged in, the field returns nil.
For more information about how the `current_user` is initialized in the `context`, refer to:
[Spree::GraphqlController: current_user](https://github.com/nebulab/solidus_graphql_api-1/blob/d21afcc8a4f5447e3b1f03ff7dc57f75d2d949ba/app/controllers/spree/graphql_controller.rb#L47-L49)
=> Add User type

lib/solidus_graphql_api/batch_loader.rb
Using also the object id makes the batch loader key unique for every query.
This is not what we want because we need the same key to batch load the queries with the same object class and relation name.
=> Remove object id from the batch loader key

app/controllers/spree/graphql_controller.rb, lib/solidus_graphql_api/context.rb, spec/lib/solidus_graphql_api/context_spec.rb, spec/requests/spree/graphql_controller_spec.rb
Extract the generation of the schema context into an own class (`SolidusGraphqlApi::Context`) and add the `current_ability`, `current_store` and `order_token` to the context.
=> Add an Object to manage the schema context

lib/solidus_graphql_api/queries/variant/images_query.rb, lib/solidus_graphql_api/types/image.rb, lib/solidus_graphql_api/types/variant.rb, schema.graphql, spec/expected_schema.graphql, spec/integration/products_spec.rb, spec/lib/solidus_graphql_api/queries/variant/images_query_spec.rb, spec/lib/solidus_graphql_api/types/variant_spec.rb
It adds the images connection field to the Variant Type and uses the `SolidusGraphqlApi::Queries::Variant::ImagesQuery` query object with batch loader to retrieve the images.
=> Add images connection field to Variant Type

spec/lib/solidus_graphql_api/queries/countries_query_spec.rb, spec/lib/solidus_graphql_api/queries/country/states_query_spec.rb, spec/lib/solidus_graphql_api/queries/option_type/option_values_query_spec.rb, spec/lib/solidus_graphql_api/queries/product/option_types_query_spec.rb, spec/lib/solidus_graphql_api/queries/product/product_properties_query_spec.rb, spec/lib/solidus_graphql_api/queries/product/variants_query_spec.rb, spec/lib/solidus_graphql_api/queries/products_query_spec.rb, spec/lib/solidus_graphql_api/queries/taxon/children_query_spec.rb, spec/lib/solidus_graphql_api/queries/taxonomies_query_spec.rb, spec/lib/solidus_graphql_api/queries/variant/images_query_spec.rb, spec/lib/solidus_graphql_api/queries/variant/option_values_query_spec.rb, spec/lib/solidus_graphql_api/queries/variant/prices_query_spec.rb
We don't care about the order of the returning result, only its contents.
=> Use match_array instead of eq in the queries specs

config/routes.rb, lib/solidus_graphql_api.rb, solidus_graphql_api.gemspec
A developer must be able to choose which tool use to integrate with the graph and we also have one less external dependency to maintain.
=> Remove graphiql-rails gem

lib/solidus_graphql_api/types/user.rb, schema.graphql, spec/expected_schema.graphql, spec/integration/current_user_spec.rb, spec/queries/currentUser.gql
Add the following `Types::Address` fields to the User Type:
- A generic `addresses` node:
- default: `[]`
- To find all of the addresses associated with a User Type:
- `defaultAddress`
- `shipAddress`
- `billAddress`
=> Add addresses field to user type

lib/solidus_graphql_api/types/query.rb, lib/solidus_graphql_api/types/store.rb, schema.graphql, spec/integration/current_store_spec.rb, spec/queries/currentStore.gql, spec/support/expected_schema.graphql
Quick Info
---
| #39 | :+1: | :+1: |
- All static fields refer to [`spree_stores`](https://github.com/solidusio/solidus/blob/475d9db5d0291dd4aeddc58ec919988c336729bb/core/db/migrate/20160101010000_solidus_one_four.rb#L930-L942
) table;
- For association, refer to [`Spree::Store`](https://github.com/solidusio/solidus/blob/40605681840bc4853c9a1cffaa8860c414c96c03/core/app/models/spree/store.rb#L12-L18) model.
- The `current_store` field returns the `context[:current_store]` in form of `Types::Store`.
For more information about how the current_user is initialized in the context, refer to:
[`SolidusGraphqlApi::Context: current_store`](https://github.com/nebulab/solidus_graphql_api-1/blob/rainerd/store-type/lib/solidus_graphql_api/context.r …
=> Add Store Type

.gitignore, Gemfile
So that gems like `graphiql-rails` are not required for regular development but can be used without bloating the `Gemfile` contents.
=> Allow developers to set a local .Gemfile

solidus_graphql_api.gemspec, spec/integration/countries_spec.rb, spec/lib/solidus_graphql_api/types/country_spec.rb, spec/lib/solidus_graphql_api/types/query_spec.rb, spec/spec_helper.rb, spec/support/matchers/graphql.rb, spec/support/queries/countries.gql, spec/support/queries/countries/states.gql, spec/support/query_results/countries.json.erb, spec/support/query_results/countries/empty_states.json.erb, spec/support/query_results/countries/states.json.erb, spec/support/shared_contexts/graphql_query_subject.rb
Change specs to use snapshot results instead of test the nodes one by one.
=> Add snapshot specs for countries query

spec/integration/current_store_spec.rb, spec/support/queries/current_store.gql, spec/support/query_results/current_store.json.erb
Change specs to use snapshot results instead of test the nodes one by one.
=> Improve current store query specs

spec/integration/countries_spec.rb, spec/integration/current_user_spec.rb, spec/integration/products_spec.rb, spec/integration/taxonomies_spec.rb, spec/support/helpers/graphql.rb, spec/support/matchers/graphql.rb
It lets the snapshot specs print a usable diff in case of not matching response.
**BEFORE**
**AFTER**
=> Improve snapshot specs error messages

lib/solidus_graphql_api/types/base/object.rb, spec/lib/solidus_graphql_api/types/base/object_spec.rb
This allows users to customize our implementation by providing the ability to remove previously defined fields (via `.remove_field`).
Fields can already be redefined by calling `field` again, so we shouldn't need much more.
=> Type Customization API

.circleci/config.yml, lib/solidus_graphql_api/types/currency.rb, lib/solidus_graphql_api/types/price.rb, lib/solidus_graphql_api/types/store.rb, schema.graphql, spec/integration/current_store_spec.rb, spec/integration/products_spec.rb, spec/lib/solidus_graphql_api/types/price_spec.rb, spec/support/expected_schema.graphql, spec/support/queries/current_store.gql, spec/support/queries/products.gql, spec/support/query_results/current_store.json.erb
Quick Info
---
| #53 | :+1: | :+1: |
- Add `currencies` in the `Types::Store`
- Add `currency` in the `Types::Price`
Note
---
[`schema-breaking-change-detection`](https://circleci.com/gh/nebulab/solidus_graphql_api-1/1404?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) fails because is necessary to deprecate the modified fields here: [`SolidusGraphqlApi::Types::PriceType`](https://github.com/nebulab/solidus_graphql_api-1/pull/62/files#diff-f22605e393de246522adef9a4984fc34L11-R11)
For the moment, since the gem hasn't yet been officially released, we don't bother to deprecate the fields.
=> Add Currency Type

spec/support/expected_schema.graphql
The expected schema includes a double GraphQL type declaration for `Currency`. This commit removes one of them.
=> Remove duplicated declaration in expected schema

lib/solidus_graphql_api/queries/completed_orders_query.rb, lib/solidus_graphql_api/queries/order/billing_address_query.rb, lib/solidus_graphql_api/queries/order/shipping_address_query.rb, lib/solidus_graphql_api/types/order.rb, lib/solidus_graphql_api/types/query.rb, schema.graphql, spec/integration/completed_orders_spec.rb, spec/lib/solidus_graphql_api/queries/completed_orders_query_spec.rb, spec/lib/solidus_graphql_api/queries/order/billing_address_query_spec.rb, spec/lib/solidus_graphql_api/queries/order/shipping_address_query_spec.rb, spec/support/expected_schema.graphql, spec/support/queries/completed_orders.gql, spec/support/queries/completed_orders/billing_address.gql, spec/support/queries/completed_orders/shipping_address.gql, spec/support/query_results/completed_orders.json.erb, spec/support/query_results/completed_orders/billing_address.json.erb, spec/support/query_results/completed_orders/shipping_address.json.erb, spec/support/shared_examples/query_is_successful.rb
Closes #45. It adds the `Order` type, based on `Spree::Order`, and the `completedOrders` query, which returns the completed orders associated to the current user.
=> Add order type and orders connection

spec/integration/queries/product_by_slug_spec.rb, spec/support/graphql/queries/product_by_slug.gql, spec/support/graphql/responses/product_by_slug.json.erb
Uses the `describe_query` and `connection_field` example groups to set the subject query and to freeze the time, and the `match_response` custom matcher to compare the query with the result.
=> Improve product by slug spec

lib/solidus_graphql_api/queries/line_item/variant_query.rb, lib/solidus_graphql_api/queries/order/line_items_query.rb, lib/solidus_graphql_api/types/line_item.rb, lib/solidus_graphql_api/types/order.rb, schema.graphql, spec/integration/queries/completed_orders_spec.rb, spec/lib/solidus_graphql_api/queries/line_item/variant_query_spec.rb, spec/lib/solidus_graphql_api/queries/order/line_items_query_spec.rb, spec/support/expected_schema.graphql, spec/support/graphql/queries/completed_orders/line_items.gql, spec/support/graphql/responses/completed_orders/line_items.json.erb
It adds the `LineItem` type, based on `Spree::LineItem`, and the `order.lineItems` connection field, which returns the line items associated to the queried order.
=> Add LineItem type and order.lineItems field

spec/support/expected_schema.graphql
The two schemas are identical but their declarations are sorted differently. Here we make them identical so to easily diff them when we change the expected schema.
=> Align expected schema with actual schema

lib/solidus_graphql_api/services/user/sign_in.rb, spec/integration/mutations/sign_in_spec.rb, spec/lib/solidus_graphql_api/services/user/sign_in_spec.rb
Before this commit, the service object "User::SignIn" returned the user
even if the password was incorrect.
=> Fix user sign-in bug

lib/solidus_graphql_api/context.rb, lib/solidus_graphql_api/types/query.rb, schema.graphql, spec/integration/queries/current_order_spec.rb, spec/lib/solidus_graphql_api/context_spec.rb, spec/support/expected_schema.graphql, spec/support/graphql/queries/current_order.gql, spec/support/graphql/responses/current_order.json.erb
It adds `current_order` to the context, which is responsible for fetching the last incomplete order from the current user or, if not found, the current order by the guest token. It returns `nil` if none of both are  found.
It also adds the `currentOrder` query, which is responsible for fetching the current order form the context and returning it.
=> Current order

lib/solidus_graphql_api.rb, lib/solidus_graphql_api/configuration.rb, lib/solidus_graphql_api/types/credit_card.rb, lib/solidus_graphql_api/types/interfaces/payment_source.rb, lib/solidus_graphql_api/types/payment_method.rb, lib/solidus_graphql_api/types/user.rb, lib/solidus_graphql_api/types/wallet_payment_source.rb, schema.graphql, spec/integration/queries/current_user_spec.rb, spec/support/expected_schema.graphql, spec/support/graphql/queries/current_user.gql, spec/support/graphql/responses/current_user.json.erb
Quick Info
---
| #41 | :+1: | :+1: |
- All static fields refer to [`spree_payment_methods`](https://github.com/solidusio/solidus/blob/475d9db5d0291dd4aeddc58ec919988c336729bb/core/db/migrate/20160101010000_solidus_one_four.rb#L347-L361) table;
- All static fields refer to [`spree_credit_cards`](https://github.com/solidusio/solidus/blob/475d9db5d0291dd4aeddc58ec919988c336729bb/core/db/migrate/20160101010000_solidus_one_four.rb#L162-L178) table;
- Adds the `PaymentSource` interface with the common Payment Source fields. And implements the interface in the type that represents the default Solidus Payment Source (Spree::CreditCard);
- All fields refer to [`Spree::WalletPaymentSource`](https://github.com/solidusio/solidus/blob/master/core/a …
=> Add Wallet Type with the connection in User Type

lib/solidus_graphql_api/queries/products_query.rb, lib/solidus_graphql_api/types/input_objects/products_query_input.rb, spec/integration/queries/products_spec.rb, spec/lib/solidus_graphql_api/queries/products_query_spec.rb
There was an issue in how the taxon argument was used in the
ProductsQueryInput, but now the argument is correctly treated as a
relay-style ID.
=> Now the ProductsQueryInput correctly accepts a relay-style ID for Taxon

README.md
Quick Info
---
| N/A | :-1: | :-1: |
The repository has recently been moved:
- From `nebulab/solidus_graphql_api-1`
- To `solidusio-contrib/solidus_graphql_api`
For this reason, these updates:
- `Code Climate CLI` `maintainability` and `test coverage` badge links;
- `CircleCI` badge link that refers to the last master branch workflow result.
=> Update badges link paths in README.md

lib/solidus_graphql_api/types/address.rb, lib/solidus_graphql_api/types/store.rb, schema.graphql, spec/support/expected_schema.graphql
Quick Info
---
| N/A | :+1: | :-1: |
Incorrectly declared fields were found in the following types:
- `SolidusGraphqlApi::Types::Address`
- `SolidusGraphqlApi::Types::Store`
All changes are made by comparing the GraphQL types with the validations present in their Solidus models.
Note
---
The null settings in `SolidusGraphqlApi::Types::Address` of these two fields:
```ruby
field :phone, String, null: false
field :zipcode, String, null: false
```
Depends since the Boolean return value of these two [`Spree::Address`](https://github.com/solidusio/solidus/blob/d456b1113de5111c3035f517ba6427e4b679bd18/core/app/models/spree/address.rb#L15-L16) instance methods (true):
```ruby
validates :zipcode, presence: true, if: :require_zipcode? …
```
=> Fix nullable fields in all types

lib/solidus_graphql_api/configuration.rb, lib/solidus_graphql_api/types/interfaces/payment_source.rb
Quick Info
---
| N/A | :-1: | :-1: |
With these changes, in the `payment_sources` configuration param, uses strings to force the correct autoloading of all the classes which are re-converted into constants during the `orphan_type` assignment and stop the circular dependencies errors in `dev` environment.
Note
---
This is a problem that probably occurred only in the development environment:
Because the `cache_classes` config flag in Solidus `cofing/environments/development.rb` configuration is usually set to `false`.
Info
---
For more information about this problem, consult these issues in `graphql-ruby`:
https://github.com/rmosolgo/graphql-ruby/issues/2716
https://github.com/rmosolgo/graphql-ruby/issues/935
=> Fix `Duplicate type definition` error during runtime changes in dev environment

lib/solidus_graphql_api/engine.rb
By default `BatchLoader` caches the loaded values[1]. To ensure that the cache is purged between requests, we have to add the `BatchLoader::Middleware` to the rails application using an initializer[2].
[1] https://github.com/exAspArk/batch-loader#caching
[2] https://api.rubyonrails.org/classes/Rails/Railtie.html
=> Add the BatchLoader middleware

lib/solidus_graphql_api/factories.rb, lib/solidus_graphql_api/factories/address_factory.rb
The Solidus address factory was changed in this commit:
https://github.com/solidusio/solidus/commit/12bdceb#diff-bcf5b7751ffe7e9a0b057cf8e449951f
and the lastname is now "Von Doe" instead of nil, this fixes the issue
modifying the original factory and setting the firstname and lastname.
=> Fix specs for Solidus version >= 2.11.0.alpha

lib/solidus_graphql_api/types/order.rb, schema.graphql, spec/support/expected_schema.graphql
When creating a new order the billing and shipping addresses are not setted yet.
=> Set shippingAddress and billingAddress order's fields as nullable

lib/solidus_graphql_api/mutations/checkout/add_addresses_to_checkout.rb, lib/solidus_graphql_api/mutations/checkout/add_payment_to_checkout.rb, lib/solidus_graphql_api/mutations/checkout/select_shipping_rate.rb, spec/integration/mutations/checkout/add_payment_to_checkout_spec.rb, spec/integration/mutations/checkout/select_shipping_rate_spec.rb
The recalculate is needed because the `Spree::OrderUpdateAttributes#apply` method doesn't call it and we have to return the update order informations.
=> Recalculate the order after update the attributes in the checkout mutations

lib/solidus_graphql_api/types/json.rb, spec/integration/queries/current_store_spec.rb, spec/support/graphql/responses/current_store.json.erb
Hey all, I've included here 2 small fixes to solidus_graphql_api ~and a temporary workaround for the [current canonical-rails problem](https://github.com/solidusio/solidus/pull/3865)~.
The first fix is to specify a factory attribute which changed in Solidus master https://github.com/solidusio/solidus/pull/3849
The second is to rescue a novel exception raised by newer versions of the gem graphql https://github.com/rmosolgo/graphql-ruby/pull/2896
=> Fix master build

solidus_graphql_api.gemspec
There's at least one part of the extension that is not compatible with
Rails < 6.1. The `ActiveModel::Errors` handling maps the error
collection assuming that what is yielded is an instance of
`ActiveModel::Error` (call to `error.attribute`):
https://github.com/solidusio-contrib/solidus_graphql_api/blob/9629e8d6b5ee5767265c3e1068a13b2677430a98/lib/solidus_graphql_api/mutations/base_mutation.rb#L36-L41
However, the [`ActiveModel::Error` object is only available from Rails
6.1](https://guides.rubyonrails.org/6_1_release_notes.html#active-model-notable-changes), and before that [it was yielded the error key and message](https://api.rubyonrails.org/v6.0.0/classes/ActiveModel/Errors.html#method-i-each).
We also bump the minimal requirement for Solidus to 2.10, as it's the
first version that …
=> Make dependency on Rails > 6.1 explicit

lib/solidus_graphql_api/context.rb, spec/lib/solidus_graphql_api/context_spec.rb
This commit fixes two bugs where an unauthenticated user was able to
impersonate a registered user.
1. When a request was made with no `Authentication` header, the system
returned as the current user the first one encountered with `NULL`
`spree_api_key`. That's because `Context#bearer_token` ended up being
`nil`, and that was given to the `#find_by(spree_api_key:
spree_api_key)` query in `Context#current_user`.
2. When a request was made with an `Authentication` header equal to `Bearer
`, the system returned as the current user the first one encountered
with `''` `spree_api_key`. That's because `Context#bearer_token` ended
up being `''`, and that was given to the `#find_by(spree_api_key:
spree_api_key)` query in `Context#current_user`.
The first one is the most likely to have hit …
=> Fix user impersonation security vulnerability

lib/solidus_graphql_api/context.rb, spec/lib/solidus_graphql_api/context_spec.rb
Orders' guest token is always populated thanks to a [`before_create`
callback on the application
layer](https://github.com/solidusio/solidus/blob/ea200dfcc03ed542ab130317ccab4f365c31af7e/core/app/models/spree/order.rb#L128).
However, it can be `NULL` in the database.
This commit makes sure that no order is returned in two situations:
1. `X-Spree-Order-Token` is not given, and it exists an order with
`NULL` guest token.
2. `X-Spree-Order-Token` is provided as an empty string, and it exists
an order with an empty string as a guest token.
Being defensive against these two options leaves us on the safe side if
business rules around the guest token change at some point in
solidus-core.
This problem is similar to what is fixed in #182
=> Fix remote possibility to return wrong current order

docs/object/optionvalue/index.html, lib/solidus_graphql_api/queries/option_value/option_type_query.rb, lib/solidus_graphql_api/types/option_value.rb, schema.graphql, spec/lib/solidus_graphql_api/queries/option_value/option_type_query_spec.rb, spec/lib/solidus_graphql_api/types/option_value_spec.rb, spec/support/expected_schema.graphql
This allows to retrieve option value values along their option type
name, description, etc. E.g.:
```graphql
query getProduct {
productBySlug(slug: "solidus-t-shirt") {
name
description
variants {
nodes {
id
sku
position
prices {
nodes {
amount
currency {
htmlEntity
}
}
}
optionValues {
nodes {
id
name
presentation
optionType {
name
position
presentation
}
}
}
}
}
}
}
```
Fixes #171
=> Add option_type field within OptionValue type

lib/solidus_graphql_api/batch_loader/has_many_through.rb, spec/lib/solidus_graphql_api/batch_loader/has_many_through_spec.rb
When a batch included two records, both of them associated to the same
target record through a `has_many_through` association, the target
record was duplicated for both parent records.
We change the name of the models used in the test to reproduce an
example with a clearer business use-case behind.
Fixes #172
=> Fix duplication of records on has_many_through associations

app/controllers/spree/graphql_controller.rb, spec/requests/spree/graphql_controller_spec.rb
When `ActiveStorage` is configured on the disk service, it needs for the
controller to include `ActiveStorage::SetCurrent` to generate URLs.
See https://api.rubyonrails.org/v6.1/classes/ActiveStorage/SetCurrent.html
=> Fix rendering blob URLs on disk storage

lib/solidus_graphql_api/types/json.rb, spec/integration/types/json_spec.rb
After the update, `GraphQL::Language::Nodes::InputObject` no longer is
enumerable without explicitly coercing it to a hash.
When the input is an `ActionController::Parameter` instance, we have to
`permit!` it before being able to coerce to hash.
@rainerdema @ChristianRimondi, it's not clear to me in which case that method can take `ActionController::Parameter` as input, I'd appreciate your insight here in case you can recall it :slightly_smiling_face:
=> Fix error on JSON type after update to graphql 1.12

README.md, config/routes.rb, lib/generators/solidus_graphql_api/install/install_generator.rb
Adds a Rails configuration option to include `/graphql` only if it is true.
Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.
The following are mandatory for all PRs:
The following are not always needed:
- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.
=> Allow GraphQL endpoint to be conditionally included. Closes #209
